--1.
select 'Customer' as TABLE_NAME, COUNT(customer_id) as NO_OF_ROWS
from customer
UNION ALL
SELECT 'PROD_CAT_INFO' AS TABLE_NAME, COUNT(PROD_CAT_CODE) AS NO_OF_ROWS
FROM prod_cat_info
UNION ALL
SELECT 'TRANSACTION_ID' AS TABLE_NAME, COUNT(transaction_id) AS NO_OF_ROWS
FROM Transactions

--2.
select count(DISTINCT transaction_id) AS Total_return
from Transactions
where Qty < 0

--3.
select Customer_id, cast(DOB as date) as DOB, Gender, City_Code 
from customer
select transaction_id, cust_id, cast(tran_date as date) as trans_date, prod_subcat_code,
Prod_cat_code, Qty, Rate, Tax,
total_amt, Store_type 
from Transactions


--4.
select 
datediff(DAY, min(tran_date), max(tran_date)) as Diff_Days,
datediff(month, min(tran_date), max(tran_date)) as Diff_Months,
datediff(year, min(tran_date),max(tran_date)) as Diff_Years
from Transactions

--5. 
select Prod_cat, prod_subcat
from prod_cat_info
where prod_subcat = 'DIY'

--------------------------------------DATA ANALYSIS--------------------------------------------------------------------
--- 1  Which channel is most frequently used for transactions? 
SELECT store_type,
 COUNT(*) AS total_transactions
FROM Transactions
GROUP BY store_type
ORDER BY total_transactions DESC;

---2 What is the count of Male and Female customers in the database?
SELECT gender,
COUNT(customer_id) AS total_customers
FROM Customer
GROUP BY gender;


---3  From which city do we have the maximum number of customers and how many?
SELECT TOP 1  city_code,
COUNT(customer_id) AS total_customers
FROM Customer
GROUP BY city_code
ORDER BY total_customers DESC;

---4 How many sub-categories are there under the Books category?
 SELECT 
  COUNT(DISTINCT prod_subcat) AS total_subcategories
FROM prod_cat_info
WHERE prod_cat = 'Books';

--5 What is the maximum quantity of products ever ordered?
SELECT 
    MAX(qty) AS max_quantity
FROM Transactions;

---6 What is the net total revenue generated in categories Electronics and Books?
SELECT 
    SUM(t.total_amt) AS net_revenue
FROM Transactions t
JOIN prod_cat_info p
ON t.prod_cat_code = p.prod_cat_code
AND t.prod_subcat_code = p.prod_sub_cat_code
WHERE p.prod_cat IN ('Electronics','Books');

--7 How many customers have >10 transactions with us, excluding returns?
SELECT 
    cust_id,
    COUNT(transaction_id) AS transaction_count
FROM Transactions
WHERE total_amt > 0
GROUP BY cust_id
HAVING COUNT(transaction_id) > 10;
 
---8 What is the combined revenue earned from the “Electronics” and “Clothing” categories, from “Flagship stores”? 
SELECT 
    SUM(t.total_amt) AS revenue
FROM Transactions t
JOIN prod_cat_info p
ON t.prod_cat_code = p.prod_cat_code
AND t.prod_subcat_code = p.prod_sub_cat_code
WHERE p.prod_cat IN ('Electronics','Clothing')
AND t.store_type LIKE 'Flagship%';

--- 9. What is the total revenue generated from “Male” customers in “Electronics” category?
---Output should display total revenue by product sub-category.
SELECT 
    p.prod_subcat,
    SUM(t.total_amt) AS total_revenue
FROM Transactions t
JOIN Customer c
ON t.cust_id = c.customer_id
JOIN prod_cat_info p
ON t.prod_cat_code = p.prod_cat_code
AND t.prod_subcat_code = p.prod_sub_cat_code
WHERE c.gender = 'M'
AND p.prod_cat = 'Electronics'
GROUP BY p.prod_subcat;

---10 What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
SELECT TOP 5
    p.prod_subcat,

      SUM(CASE 
        WHEN t.total_amt > 0 THEN t.total_amt 
        ELSE 0 
    END) 
    /
    (SELECT SUM(total_amt) 
     FROM Transactions 
     WHERE total_amt > 0) 
    AS sales_percentage,

    SUM(CASE 
        WHEN t.total_amt < 0 THEN t.total_amt 
        ELSE 0 
    END)
    /
    (SELECT SUM(total_amt) 
     FROM Transactions 
     WHERE total_amt < 0) 
    AS return_percentage

FROM Transactions t
JOIN prod_cat_info p
ON t.prod_cat_code = p.prod_cat_code
AND t.prod_subcat_code = p.prod_sub_cat_code

GROUP BY p.prod_subcat
ORDER BY sales_percentage DESC;

---11  For all customers aged between 25 to 35 years, find the net total revenue generated by these consumers in the last 30 days of transactions 
--from the maximum transaction date available in the data.

SELECT 
    SUM(t.total_amt) AS net_revenue
FROM Transactions t
JOIN Customer c
ON t.cust_id = c.customer_id
WHERE 
DATEDIFF(YEAR, c.DOB, GETDATE()) BETWEEN 25 AND 35
AND t.tran_date >= DATEADD(DAY, -30, 
    (SELECT MAX(tran_date) FROM Transactions)
);

 ---12 Which product category has seen the maximum value of returns in the last 3 months of transactions?
 SELECT TOP 1
    p.prod_cat,
    SUM(t.total_amt) AS total_returns
FROM Transactions t
JOIN prod_cat_info p
ON t.prod_cat_code = p.prod_cat_code
AND t.prod_subcat_code = p.prod_sub_cat_code
WHERE t.total_amt < 0
AND t.tran_date >= DATEADD(MONTH, -3,
    (SELECT MAX(tran_date) FROM Transactions)
)
GROUP BY p.prod_cat
ORDER BY total_returns ASC;

--13 Which store-type sells the maximum products, by value of sales amount and by quantity sold?
SELECT 
    store_type,
    SUM(total_amt) AS total_sales_value,
    SUM(qty) AS total_quantity_sold
FROM Transactions
WHERE total_amt > 0
GROUP BY store_type
ORDER BY total_sales_value DESC;

---14 What are the categories for which average revenue is above the overall average?
SELECT 
    p.prod_cat,
    AVG(t.total_amt) AS avg_revenue
FROM Transactions t
JOIN prod_cat_info p
ON t.prod_cat_code = p.prod_cat_code
AND t.prod_subcat_code = p.prod_sub_cat_code
GROUP BY p.prod_cat
HAVING AVG(t.total_amt) >
(
    SELECT AVG(total_amt)
    FROM Transactions
);

---15  Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.
SELECT 
    p.prod_subcat,
    AVG(t.total_amt) AS avg_revenue,
    SUM(t.total_amt) AS total_revenue
FROM Transactions t
JOIN prod_cat_info p
ON t.prod_cat_code = p.prod_cat_code
AND t.prod_subcat_code = p.prod_sub_cat_code
WHERE p.prod_cat_code IN
(
    SELECT TOP 5 
        prod_cat_code
    FROM Transactions
    GROUP BY prod_cat_code
    ORDER BY SUM(qty) DESC
)
GROUP BY p.prod_subcat;






